const $=s=>document.querySelector(s);let itens=[];
const dinheiro=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function produtos(){try{return JSON.parse(localStorage.getItem('produtos')||'[]')}catch{return[]}}
function imgHtml(src,nome){return src?`<img src="${src}" alt="" onerror="this.outerHTML='<div class=&quot;fotoFallback&quot;>📦</div>'">`:'<div class="fotoFallback">📦</div>'}
function renderCatalogo(){const q=($('#buscaPeca').value||'').toLowerCase();const ps=produtos().filter(p=>String(p.nome||'').toLowerCase().includes(q));$('#listaPecas').innerHTML=ps.length?ps.map((p,i)=>`<div class="pecaServico">${imgHtml(p.imagem,p.nome)}<div><h4>${p.nome||'Produto'}</h4><small>Estoque: ${p.quantidade??'-'}</small></div><input class="precoServico" type="number" min="0" step="0.01" value="${Number(p.precoConserto??p.preco??0)}" data-preco="${i}"><button class="btnAdicionarPeca" data-add="${i}">Adicionar</button></div>`).join(''):'<div class="vazioServico">Nenhuma peça encontrada.</div>';$('#listaPecas').onclick=e=>{let b=e.target.closest('[data-add]');if(!b)return;let p=ps[+b.dataset.add],inp=$(`[data-preco="${b.dataset.add}"]`);itens.push({id:Date.now()+Math.random(),nome:p.nome||'Produto',imagem:p.imagem||'',preco:Number(inp.value||0),origem:'catalogo'});renderItens()}}
function renderItens(){let total=itens.reduce((s,x)=>s+Number(x.preco||0),0);$('#totalServico').textContent=$('#totalRodape').textContent=dinheiro(total);$('#contadorItens').textContent=itens.length?`${itens.length} ${itens.length===1?'item':'itens'} adicionado${itens.length===1?'':'s'}`:'Nenhum item adicionado';$('#itensServico').innerHTML=itens.length?itens.map(x=>`<div class="itemServico">${imgHtml(x.imagem,x.nome)}<div><h4>${x.nome}</h4><small>${x.origem==='manual'?'Serviço manual':'Peça'}${x.email?' • '+x.email:''}</small></div><p>${dinheiro(x.preco)}</p><button class="removerItem" data-rem="${x.id}">×</button></div>`).join(''):'<div class="vazioServico">Adicione peças ou itens manuais para montar o serviço.</div>';$('#itensServico').onclick=e=>{let b=e.target.closest('[data-rem]');if(b){itens=itens.filter(x=>String(x.id)!==b.dataset.rem);renderItens()}}}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function imprimir(){
 if(!itens.length)return alert('Adicione pelo menos um item ao serviço.');
 const nome=$('#nomeServico').value.trim()||'Cliente / Serviço';
 const obs=$('#obsServico').value.trim();
 const itensFinalizados=itens.map(x=>({...x}));
 const total=itensFinalizados.reduce((s,x)=>s+Number(x.preco||0),0);
 const numero=String(Date.now()).slice(-6);
 const linhas=itensFinalizados.map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.nome)}</strong>${x.email?`<div class="cred">Login: ${esc(x.email)}</div>`:''}${x.senha?`<div class="cred">Senha: ${esc(x.senha)}</div>`:''}</td><td class="valor">${dinheiro(x.preco)}</td></tr>`).join('');
 const w=window.open('','_blank');
 if(!w)return alert('O navegador bloqueou a janela de impressão. Permita pop-ups para este site.');
 w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Comprovante ${numero}</title><style>
 *{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#171717;margin:0;background:#f3f5f8}.comprovante{width:min(100%,720px);margin:22px auto;background:#fff;padding:28px 30px;border-radius:18px;box-shadow:0 8px 35px #00000012}.cab{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;padding-bottom:18px;border-bottom:2px dashed #d7dce4}.marca{font-size:25px;font-weight:900;color:#0667ff;letter-spacing:.5px}.sub{font-size:12px;color:#777;margin-top:4px}.doc{text-align:right;font-size:12px;color:#666}.doc strong{display:block;color:#171717;font-size:14px;margin-bottom:4px}.cliente{margin:18px 0;padding:14px 16px;border:1px solid #e2e6ec;border-radius:12px;background:#fafbfc}.cliente b{font-size:16px}.obs{font-size:13px;color:#555;margin-top:5px;white-space:pre-wrap}table{width:100%;border-collapse:collapse;margin-top:8px}th{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:#777;text-align:left;padding:10px 8px;border-bottom:1px solid #dfe3e8}td{padding:14px 8px;border-bottom:1px dashed #dfe3e8;font-size:14px}.valor{text-align:right;white-space:nowrap;font-weight:700}.cred{font-size:11px;color:#666;margin-top:4px}.totais{margin-top:18px;border-top:2px solid #171717;padding-top:15px;display:flex;justify-content:space-between;align-items:center}.totais span{font-size:14px;font-weight:700}.totais strong{font-size:27px;color:#0667ff}.msg{text-align:center;margin:28px 0 8px;font-size:12px;color:#777}.assinaturas{display:flex;gap:30px;margin-top:45px}.assinaturas div{flex:1;border-top:1px solid #999;text-align:center;padding-top:7px;font-size:10px;color:#777}.acoes{text-align:center;margin:0 auto 20px}.acoes button{border:0;border-radius:10px;background:#0667ff;color:white;font-weight:700;padding:12px 20px;cursor:pointer}@media print{body{background:#fff}.comprovante{width:100%;margin:0;padding:8mm;box-shadow:none;border-radius:0}.acoes{display:none}@page{margin:8mm}}
 </style></head><body><div class="comprovante"><div class="cab"><div><div class="marca">GUSTAVOCELL</div><div class="sub">Comprovante de serviço</div></div><div class="doc"><strong>OS #${numero}</strong>${new Date().toLocaleDateString('pt-BR')}<br>${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</div></div><div class="cliente"><b>${esc(nome)}</b>${obs?`<div class="obs">${esc(obs)}</div>`:''}</div><table><thead><tr><th>#</th><th>Item / Serviço</th><th style="text-align:right">Valor</th></tr></thead><tbody>${linhas}</tbody></table><div class="totais"><span>TOTAL</span><strong>${dinheiro(total)}</strong></div><div class="msg">Obrigado pela preferência! • Guarde este comprovante.</div><div class="assinaturas"><div>Cliente</div><div>GustavoCell</div></div></div><div class="acoes"><button onclick="window.print()">🖨️ Imprimir novamente</button></div><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);
 w.document.close();
 // Finalizou: limpa a OS atual assim que a janela de impressão foi criada.
 itens=[];
 $('#nomeServico').value='';
 $('#obsServico').value='';
 renderItens();
}
const toggleLista=$('#toggleListaPecas'),conteudoLista=$('#conteudoListaPecas');
toggleLista.onclick=()=>{const aberto=conteudoLista.classList.toggle('aberto');toggleLista.classList.toggle('aberto',aberto);toggleLista.setAttribute('aria-expanded',String(aberto));};
$('#mostrarSenha').onchange=e=>{$('#manualSenha').type=e.target.checked?'text':'password'};
$('#adicionarManual').onclick=()=>{const nome=$('#manualNome').value.trim(),preco=Number($('#manualPreco').value||0),email=$('#manualEmail').value.trim(),senha=$('#manualSenha').value;if(!nome)return alert('Digite o nome do serviço.');itens.push({id:Date.now()+Math.random(),nome,imagem:'',preco,origem:'manual',email,senha});$('#manualNome').value='';$('#manualPreco').value='';$('#manualEmail').value='';$('#manualSenha').value='';$('#mostrarSenha').checked=false;$('#manualSenha').type='password';renderItens();};
$('#buscaPeca').addEventListener('input',renderCatalogo);$('#limparServico').onclick=()=>{if(itens.length&&confirm('Limpar todos os itens deste serviço?')){itens=[];renderItens()}};$('#finalizarServico').onclick=imprimir;window.addEventListener('storage',e=>{if(e.key==='produtos')renderCatalogo()});renderCatalogo();renderItens();